### ISSUE TITLE
Error al extraer JSON para el intervalo "Octava"

### ISSUE THREAD

**Issue by javiciier** [cabrero/ipm2021_01_server#1]
Al hacer una petición a http://127.0.0.1:5000/intervals , en el JSON recibido el último elemento (Octava) tiene como clave "8j", pero tanto en la documentación de la práctica como en el fichero intervalos.csv aparece "8a". ¿Cuál es el correcto?

**Comment by cabrero** [comment]
Independientemente de cual ser más correcta, no pueden ser distintas en las dos entradas del api.

Lo cambio en /intervals
